version: 2
jobs:
  build:
    docker:
      - image: golang:1.16-stretch
    steps:
      - checkout
      - run:
          name: "Build the binary"
          command: go build -o pickem .
      - run:
          name: "Generate current results"
          command: ./pickem

workflows:
  version: 2
  build:
    jobs:
      - build
